README updates
rhysd/Mstdn pull request #26
Opened 2017-05-28 04:13 UTC by sumnerevans

Updated README:

- consistent 80 character line limit
- grammar updates

2017-05-28 17:41 UTC, rhysd commented
Thank you for updates! They're helpful because I'm not a native English speaker.

2017-05-28 17:58 UTC, rhysd requested changes

2017-05-28 17:58 UTC, rhysd commented on README.md
> +user.  When you click menu item of non-current user, application window will be
This should be one space ('user. When...')

2017-05-29 02:53 UTC, sumnerevans commented on README.md
> +user.  When you click menu item of non-current user, application window will be
Good catch. Fixed!

2017-05-29 03:00 UTC, rhysd approved these changes

2017-05-29 03:00 UTC, merged

2017-05-29 03:00 UTC, rhysd commented
Merged. Thank you.